/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.Handler;

/**
 *
 * @author super
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private Handler handler;
    private String novelName;
    private String coverPath;
    private int volumeNumber;
    
    private Desktop desktop = java.awt.Desktop.getDesktop();
    private URI browseURL;
    
    private File cwd = new File(System.getProperty("user.dir"));
    
    private Image img =(new ImageIcon(getClass().getResource("/rsc/icon.png"))).getImage();
    public GUI(Handler handler) {
        this.handler = handler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceSelectionPanel = new javax.swing.JPanel();
        homeIconLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeNovelPlanetIconLabel = new javax.swing.JLabel();
        homeWuxiaWorldIconLabel = new javax.swing.JLabel();
        homeWuxiaCoWorldIconLabel = new javax.swing.JLabel();
        homeNovelPlanetTextField = new javax.swing.JLabel();
        homeNovelPlanetTextField1 = new javax.swing.JLabel();
        homeNovelPlanetTextField2 = new javax.swing.JLabel();
        wuxiaWorldPanel = new javax.swing.JPanel();
        wuxiaWorldRunButton = new javax.swing.JButton();
        wuxiaWorldUrlLabel = new javax.swing.JLabel();
        wuxiaWorldUrlTextField = new javax.swing.JTextField();
        wuxiaWorldCoverLabel = new javax.swing.JLabel();
        wuxiaWorldCoverTextField = new javax.swing.JTextField();
        wuxiaWorldCoverButton = new javax.swing.JButton();
        wuxiaWorldVolumeLabel1 = new javax.swing.JLabel();
        wuxiaWorldVolumeTextField1 = new javax.swing.JTextField();
        wuxiaWorldScrollPanel = new javax.swing.JScrollPane();
        wuxiaWorldLogTextArea = new javax.swing.JTextArea();
        novelPlanetPanel = new javax.swing.JPanel();
        novelPlanetLabel = new javax.swing.JLabel();
        wuxiaCoWorldPanel = new javax.swing.JPanel();
        wuxiaCoWorldLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dr_nyt's NovelScraper");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(img);

        sourceSelectionPanel.setBackground(new java.awt.Color(2, 39, 87));
        sourceSelectionPanel.setForeground(new java.awt.Color(255, 255, 255));

        homeIconLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/home.png"))); // NOI18N
        homeIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeIconLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeIconLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sourceSelectionPanelLayout = new javax.swing.GroupLayout(sourceSelectionPanel);
        sourceSelectionPanel.setLayout(sourceSelectionPanelLayout);
        sourceSelectionPanelLayout.setHorizontalGroup(
            sourceSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceSelectionPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(homeIconLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sourceSelectionPanelLayout.setVerticalGroup(
            sourceSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceSelectionPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeIconLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(14, 78, 159));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Agency FB", 1, 60)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("NovelScraper");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(643, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap())
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        homeNovelPlanetIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/NovelPlanet Logo.png"))); // NOI18N
        homeNovelPlanetIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeNovelPlanetIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeNovelPlanetIconLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeNovelPlanetIconLabelMouseExited(evt);
            }
        });

        homeWuxiaWorldIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/WuxiaWorld Logo.png"))); // NOI18N
        homeWuxiaWorldIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeWuxiaWorldIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeWuxiaWorldIconLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeWuxiaWorldIconLabelMouseExited(evt);
            }
        });

        homeWuxiaCoWorldIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/m.WuxiaWorld Logo.png"))); // NOI18N
        homeWuxiaCoWorldIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeWuxiaCoWorldIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeWuxiaCoWorldIconLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeWuxiaCoWorldIconLabelMouseExited(evt);
            }
        });

        homeNovelPlanetTextField.setBackground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        homeNovelPlanetTextField.setForeground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField.setText("WuxiaWorldCo");

        homeNovelPlanetTextField1.setBackground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        homeNovelPlanetTextField1.setForeground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField1.setText("NovelPlanet");

        homeNovelPlanetTextField2.setBackground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        homeNovelPlanetTextField2.setForeground(new java.awt.Color(2, 39, 87));
        homeNovelPlanetTextField2.setText("WuxiaWorld");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(homeNovelPlanetIconLabel)
                        .addGap(120, 120, 120)
                        .addComponent(homeWuxiaWorldIconLabel)
                        .addGap(111, 111, 111)
                        .addComponent(homeWuxiaCoWorldIconLabel))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(homeNovelPlanetTextField1)
                        .addGap(93, 93, 93)
                        .addComponent(homeNovelPlanetTextField2)
                        .addGap(67, 67, 67)
                        .addComponent(homeNovelPlanetTextField)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeWuxiaCoWorldIconLabel)
                    .addComponent(homeWuxiaWorldIconLabel)
                    .addComponent(homeNovelPlanetIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeNovelPlanetTextField)
                    .addComponent(homeNovelPlanetTextField1)
                    .addComponent(homeNovelPlanetTextField2))
                .addContainerGap(431, Short.MAX_VALUE))
        );

        wuxiaWorldPanel.setBackground(new java.awt.Color(255, 255, 255));

        wuxiaWorldRunButton.setBackground(new java.awt.Color(2, 39, 87));
        wuxiaWorldRunButton.setForeground(new java.awt.Color(255, 255, 255));
        wuxiaWorldRunButton.setText("Run");
        wuxiaWorldRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wuxiaWorldRunButtonActionPerformed(evt);
            }
        });

        wuxiaWorldUrlLabel.setBackground(new java.awt.Color(2, 39, 87));
        wuxiaWorldUrlLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        wuxiaWorldUrlLabel.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldUrlLabel.setText("URL :");

        wuxiaWorldUrlTextField.setBackground(new java.awt.Color(255, 255, 255));
        wuxiaWorldUrlTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wuxiaWorldUrlTextField.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldUrlTextField.setToolTipText("");

        wuxiaWorldCoverLabel.setBackground(new java.awt.Color(2, 39, 87));
        wuxiaWorldCoverLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        wuxiaWorldCoverLabel.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldCoverLabel.setText("Cover :");

        wuxiaWorldCoverTextField.setEditable(false);
        wuxiaWorldCoverTextField.setBackground(new java.awt.Color(255, 255, 255));
        wuxiaWorldCoverTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wuxiaWorldCoverTextField.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldCoverTextField.setText("rsc/cover.png");
        wuxiaWorldCoverTextField.setToolTipText("");

        wuxiaWorldCoverButton.setBackground(new java.awt.Color(2, 39, 87));
        wuxiaWorldCoverButton.setForeground(new java.awt.Color(255, 255, 255));
        wuxiaWorldCoverButton.setText("Browse");
        wuxiaWorldCoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wuxiaWorldCoverButtonActionPerformed(evt);
            }
        });

        wuxiaWorldVolumeLabel1.setBackground(new java.awt.Color(2, 39, 87));
        wuxiaWorldVolumeLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        wuxiaWorldVolumeLabel1.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldVolumeLabel1.setText("Volume :");

        wuxiaWorldVolumeTextField1.setBackground(new java.awt.Color(255, 255, 255));
        wuxiaWorldVolumeTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wuxiaWorldVolumeTextField1.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaWorldVolumeTextField1.setText("All");
        wuxiaWorldVolumeTextField1.setToolTipText("Change this to a number to compile a specific volume.");
        wuxiaWorldVolumeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wuxiaWorldVolumeTextField1ActionPerformed(evt);
            }
        });

        wuxiaWorldLogTextArea.setEditable(false);
        wuxiaWorldLogTextArea.setBackground(new java.awt.Color(255, 255, 255));
        wuxiaWorldLogTextArea.setColumns(20);
        wuxiaWorldLogTextArea.setRows(5);
        wuxiaWorldLogTextArea.setText("Log:\n");
        wuxiaWorldLogTextArea.setToolTipText("");
        wuxiaWorldScrollPanel.setViewportView(wuxiaWorldLogTextArea);

        new SmartScroller( wuxiaWorldScrollPanel );

        javax.swing.GroupLayout wuxiaWorldPanelLayout = new javax.swing.GroupLayout(wuxiaWorldPanel);
        wuxiaWorldPanel.setLayout(wuxiaWorldPanelLayout);
        wuxiaWorldPanelLayout.setHorizontalGroup(
            wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wuxiaWorldPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(wuxiaWorldPanelLayout.createSequentialGroup()
                        .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wuxiaWorldPanelLayout.createSequentialGroup()
                                .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(wuxiaWorldRunButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wuxiaWorldPanelLayout.createSequentialGroup()
                                        .addComponent(wuxiaWorldVolumeLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wuxiaWorldVolumeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(wuxiaWorldPanelLayout.createSequentialGroup()
                                .addComponent(wuxiaWorldCoverLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wuxiaWorldCoverTextField)))
                        .addGap(18, 18, 18)
                        .addComponent(wuxiaWorldCoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wuxiaWorldPanelLayout.createSequentialGroup()
                        .addComponent(wuxiaWorldUrlLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wuxiaWorldUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wuxiaWorldScrollPanel))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        wuxiaWorldPanelLayout.setVerticalGroup(
            wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wuxiaWorldPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wuxiaWorldUrlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wuxiaWorldUrlTextField))
                .addGap(18, 18, 18)
                .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wuxiaWorldCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wuxiaWorldCoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wuxiaWorldCoverTextField))
                .addGap(18, 18, 18)
                .addGroup(wuxiaWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wuxiaWorldVolumeTextField1)
                    .addComponent(wuxiaWorldVolumeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(wuxiaWorldRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wuxiaWorldScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        novelPlanetPanel.setBackground(new java.awt.Color(255, 255, 255));

        novelPlanetLabel.setForeground(new java.awt.Color(2, 39, 87));
        novelPlanetLabel.setText("Atleast the void is full of emptiness");

        javax.swing.GroupLayout novelPlanetPanelLayout = new javax.swing.GroupLayout(novelPlanetPanel);
        novelPlanetPanel.setLayout(novelPlanetPanelLayout);
        novelPlanetPanelLayout.setHorizontalGroup(
            novelPlanetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novelPlanetPanelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(novelPlanetLabel)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        novelPlanetPanelLayout.setVerticalGroup(
            novelPlanetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novelPlanetPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(novelPlanetLabel)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        wuxiaCoWorldPanel.setBackground(new java.awt.Color(255, 255, 255));

        wuxiaCoWorldLabel.setForeground(new java.awt.Color(2, 39, 87));
        wuxiaCoWorldLabel.setText("Another one? How much empty do you even have?");

        javax.swing.GroupLayout wuxiaCoWorldPanelLayout = new javax.swing.GroupLayout(wuxiaCoWorldPanel);
        wuxiaCoWorldPanel.setLayout(wuxiaCoWorldPanelLayout);
        wuxiaCoWorldPanelLayout.setHorizontalGroup(
            wuxiaCoWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wuxiaCoWorldPanelLayout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(wuxiaCoWorldLabel)
                .addGap(204, 204, 204))
        );
        wuxiaCoWorldPanelLayout.setVerticalGroup(
            wuxiaCoWorldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wuxiaCoWorldPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(wuxiaCoWorldLabel)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(wuxiaWorldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(novelPlanetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(wuxiaCoWorldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(wuxiaWorldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(novelPlanetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(wuxiaCoWorldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        wuxiaWorldPanel.setVisible(false);
        novelPlanetPanel.setVisible(false);
        wuxiaCoWorldPanel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sourceSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sourceSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconLabelMouseEntered
        ImageIcon hoverIcon = new ImageIcon(getClass().getResource("/rsc/home-hover.png"));
        homeIconLabel.setIcon(hoverIcon);
    }//GEN-LAST:event_homeIconLabelMouseEntered

    private void homeIconLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconLabelMouseExited
        ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/rsc/home.png"));
        homeIconLabel.setIcon(defaultIcon);
    }//GEN-LAST:event_homeIconLabelMouseExited

    private void homeNovelPlanetIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNovelPlanetIconLabelMouseEntered
        ImageIcon hoverIcon = new ImageIcon(getClass().getResource("/rsc/NovelPlanet Logo-hover.png"));
        homeNovelPlanetIconLabel.setIcon(hoverIcon);
    }//GEN-LAST:event_homeNovelPlanetIconLabelMouseEntered

    private void homeNovelPlanetIconLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNovelPlanetIconLabelMouseExited
        ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/rsc/NovelPlanet Logo.png"));
        homeNovelPlanetIconLabel.setIcon(defaultIcon);
    }//GEN-LAST:event_homeNovelPlanetIconLabelMouseExited

    private void homeWuxiaWorldIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaWorldIconLabelMouseEntered
        ImageIcon hoverIcon = new ImageIcon(getClass().getResource("/rsc/WuxiaWorld Logo-hover.png"));
        homeWuxiaWorldIconLabel.setIcon(hoverIcon);
    }//GEN-LAST:event_homeWuxiaWorldIconLabelMouseEntered

    private void homeWuxiaWorldIconLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaWorldIconLabelMouseExited
        ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/rsc/WuxiaWorld Logo.png"));
        homeWuxiaWorldIconLabel.setIcon(defaultIcon);
    }//GEN-LAST:event_homeWuxiaWorldIconLabelMouseExited

    private void homeWuxiaCoWorldIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaCoWorldIconLabelMouseEntered
        ImageIcon hoverIcon = new ImageIcon(getClass().getResource("/rsc/m.WuxiaWorld Logo-hover.png"));
        homeWuxiaCoWorldIconLabel.setIcon(hoverIcon);
    }//GEN-LAST:event_homeWuxiaCoWorldIconLabelMouseEntered

    private void homeWuxiaCoWorldIconLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaCoWorldIconLabelMouseExited
        ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/rsc/m.WuxiaWorld Logo.png"));
        homeWuxiaCoWorldIconLabel.setIcon(defaultIcon);
    }//GEN-LAST:event_homeWuxiaCoWorldIconLabelMouseExited

//    Uncomment his section when undecorated frame is used. Ask dr_nyt for more info.
//    int xx = 0;
//    int yy = 0;
    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
//        xx=evt.getX();
//        yy=evt.getY();  
    }//GEN-LAST:event_headerPanelMousePressed

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
//        int x=evt.getXOnScreen();
//        int y=evt.getYOnScreen();
//        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void homeWuxiaWorldIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaWorldIconLabelMouseClicked

        this.homePanel.setVisible(false);
        this.wuxiaCoWorldPanel.setVisible(false);
        this.novelPlanetPanel.setVisible(false);
        this.wuxiaWorldPanel.setVisible(true);
        this.titleLabel.setText("WuxiaWorld");
    }//GEN-LAST:event_homeWuxiaWorldIconLabelMouseClicked
    
    private void wuxiaWorldRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wuxiaWorldRunButtonActionPerformed
        this.wuxiaWorldLogTextArea.setText("Log:\n");
        this.novelName = this.wuxiaWorldUrlTextField.getText();
        this.coverPath = this.wuxiaWorldCoverTextField.getText();
        try{
            this.volumeNumber = Integer.parseInt(this.wuxiaWorldVolumeTextField1.getText());
        } catch(Exception e){
            if(!this.wuxiaWorldVolumeTextField1.getText().toLowerCase().equals("all"))
            {
                this.logError("Incorrect Volume Number\n" + 
                        e.toString());
                return;
            }
            else
            {
                this.volumeNumber = 0;
            }
        }
        
        if(!this.novelName.toLowerCase().contains("https://www.wuxiaworld.com/novel/"))
        {
            this.logError("Incorrect URL!\n" +
                            "This source only accepts links from https://www.wuxiaworld.com");
            return;
        }
        
        
        handler.setWuxiaWorld(this.novelName, this.coverPath, this.volumeNumber, this.handler);
        this.lock();
    }//GEN-LAST:event_wuxiaWorldRunButtonActionPerformed

    private void wuxiaWorldCoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wuxiaWorldCoverButtonActionPerformed
        JFileChooser wuxiaWorldCoverChooser = new JFileChooser();
        wuxiaWorldCoverChooser.setCurrentDirectory(cwd);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "png");
        wuxiaWorldCoverChooser.setFileFilter(filter);
        wuxiaWorldCoverChooser.showOpenDialog(null);
        File wuxiaWorldCover = wuxiaWorldCoverChooser.getSelectedFile();
        this.wuxiaWorldCoverTextField.setText(wuxiaWorldCover.getAbsolutePath());
    }//GEN-LAST:event_wuxiaWorldCoverButtonActionPerformed

    private void homeIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconLabelMouseClicked
        
        this.wuxiaWorldPanel.setVisible(false);
        this.wuxiaCoWorldPanel.setVisible(false);
        this.novelPlanetPanel.setVisible(false);
        this.homePanel.setVisible(true);
        this.titleLabel.setText("NovelScraper");
    }//GEN-LAST:event_homeIconLabelMouseClicked

    private void wuxiaWorldVolumeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wuxiaWorldVolumeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wuxiaWorldVolumeTextField1ActionPerformed

    private void homeNovelPlanetIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNovelPlanetIconLabelMouseClicked
        this.homePanel.setVisible(false);
        this.wuxiaCoWorldPanel.setVisible(false);
        this.wuxiaWorldPanel.setVisible(false);
        this.novelPlanetPanel.setVisible(true);
        this.titleLabel.setText("NovelPlanet");
    }//GEN-LAST:event_homeNovelPlanetIconLabelMouseClicked

    private void homeWuxiaCoWorldIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeWuxiaCoWorldIconLabelMouseClicked
        this.homePanel.setVisible(false);
        this.wuxiaWorldPanel.setVisible(false);
        this.novelPlanetPanel.setVisible(false);
        this.wuxiaCoWorldPanel.setVisible(true);
        this.titleLabel.setText("WuxiaWorldCo");
    }//GEN-LAST:event_homeWuxiaCoWorldIconLabelMouseClicked

    public JButton getWuxiaWorldRunButton() {
        return wuxiaWorldRunButton;
    }

    public JButton getWuxiaWorldCoverButton() {
        return wuxiaWorldCoverButton;
    }

    public void log(String text)
    {
        this.wuxiaWorldLogTextArea.setForeground(Color.black);
        this.wuxiaWorldLogTextArea.append(text + "\n");
    }
    
    public void logError(String text)
    {
        this.wuxiaWorldLogTextArea.setForeground(Color.red);
        this.wuxiaWorldLogTextArea.append("An Error Ocurred!\n");
        this.wuxiaWorldLogTextArea.append("==========================================\n");
        this.wuxiaWorldLogTextArea.append("\n");
        this.wuxiaWorldLogTextArea.append(text + "\n");
        this.wuxiaWorldLogTextArea.append("\n");
        this.wuxiaWorldLogTextArea.append("==========================================\n");
        this.wuxiaWorldLogTextArea.append("If this issue persists, open and issue here: https://github.com/dr-nyt/Translated-Novel-Downloader/issues \n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    public void lock()
    {
        this.wuxiaWorldRunButton.setEnabled(false);
        this.wuxiaWorldCoverButton.setEnabled(false);
    }
    
    public void unLock()
    {
        this.wuxiaWorldRunButton.setEnabled(true);
        this.wuxiaWorldCoverButton.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel homeIconLabel;
    private javax.swing.JLabel homeNovelPlanetIconLabel;
    private javax.swing.JLabel homeNovelPlanetTextField;
    private javax.swing.JLabel homeNovelPlanetTextField1;
    private javax.swing.JLabel homeNovelPlanetTextField2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeWuxiaCoWorldIconLabel;
    private javax.swing.JLabel homeWuxiaWorldIconLabel;
    private javax.swing.JLabel novelPlanetLabel;
    private javax.swing.JPanel novelPlanetPanel;
    private javax.swing.JPanel sourceSelectionPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wuxiaCoWorldLabel;
    private javax.swing.JPanel wuxiaCoWorldPanel;
    private javax.swing.JButton wuxiaWorldCoverButton;
    private javax.swing.JLabel wuxiaWorldCoverLabel;
    private javax.swing.JTextField wuxiaWorldCoverTextField;
    private javax.swing.JTextArea wuxiaWorldLogTextArea;
    private javax.swing.JPanel wuxiaWorldPanel;
    private javax.swing.JButton wuxiaWorldRunButton;
    private javax.swing.JScrollPane wuxiaWorldScrollPanel;
    private javax.swing.JLabel wuxiaWorldUrlLabel;
    private javax.swing.JTextField wuxiaWorldUrlTextField;
    private javax.swing.JLabel wuxiaWorldVolumeLabel1;
    private javax.swing.JTextField wuxiaWorldVolumeTextField1;
    // End of variables declaration//GEN-END:variables
}
